// signals-awesome/react-app/src/pages/Mall.tsx
import { memo, useState } from "react";

const Main = memo(({ setCart }: any) => {
  console.log('<Main />');

  return (
    <div>
      <Product setCart={setCart} />
    </div>
  )
})

export const Product = memo(({ setCart }: any) => {
  console.log('<Product />');
  return (
    <div>
      <button onClick={() => {
        setCart((cart: any) => [...cart, `product`])
      }}>Add to cart</button>
    </div >
  )
})

const NavBar = memo(({ cart }: any) => {
  console.log('<NavBar />');

  return (
    <div>
      <Cart cart={cart} />
    </div>
  )
})

const Cart = memo(({ cart }: any) => {
  console.log('<Cart />');

  return (
    <div>Cart: {JSON.stringify(cart)}</div>
  )
})


export default function Mall() {
  console.log('<Mall />');

  const [cart, setCart] = useState([]);

  return (
    <div>
      <Main setCart={setCart} />
      <NavBar cart={cart} />
    </div>
  )
}

// signals-awesome/solid-app/src/pages/mall.jsx
import { createSignal } from "solid-js";
import { createStore } from "solid-js/store";
import { render } from "solid-js/web";

const [cart, setCart] = createSignal([]);


const Main = () => {
  console.log('<Main />');
  return (
    <div>
      <Product />
    </div>
  )
}

export const Product = () => {
  console.log('<Product />');
  return (
    <div>
      <button onClick={() => {
        const prevCart = cart();
        setCart([...prevCart, 'product'])
      }}>Add to cart</button>
    </div >
  )
}

const NavBar = () => {
  console.log('<NavBar />');
  return (
    <div>
      <Cart />
    </div>
  )
}

const Cart = () => {
  console.log('<Cart />');
  return (
    <div>Cart: {JSON.stringify(cart())}</div>
  )
}

export default function Mall() {

  console.log('<Mall />');
  return (
    <div>
      <Main />
      <NavBar />
    </div>
  )
}
